// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfgan9R6LtVszLeLPQmOfpacXN9bS_WGg',
    appId: '1:925380284779:web:aca1ec5ac9491d3c757c2e',
    messagingSenderId: '925380284779',
    projectId: 'dune-e9f08',
    authDomain: 'dune-e9f08.firebaseapp.com',
    databaseURL: 'https://dune-e9f08-default-rtdb.firebaseio.com',
    storageBucket: 'dune-e9f08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnYWerDvFEHUExL07BgbynIT99qtVLrvc',
    appId: '1:925380284779:android:b95534ebd8564ba8757c2e',
    messagingSenderId: '925380284779',
    projectId: 'dune-e9f08',
    databaseURL: 'https://dune-e9f08-default-rtdb.firebaseio.com',
    storageBucket: 'dune-e9f08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Appzxh68RDN2_ZfdJcORZ6WfO_KtPHM',
    appId: '1:925380284779:ios:99f6e6f26a5ad52b757c2e',
    messagingSenderId: '925380284779',
    projectId: 'dune-e9f08',
    databaseURL: 'https://dune-e9f08-default-rtdb.firebaseio.com',
    storageBucket: 'dune-e9f08.appspot.com',
    iosBundleId: 'com.example.dunes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Appzxh68RDN2_ZfdJcORZ6WfO_KtPHM',
    appId: '1:925380284779:ios:99f6e6f26a5ad52b757c2e',
    messagingSenderId: '925380284779',
    projectId: 'dune-e9f08',
    databaseURL: 'https://dune-e9f08-default-rtdb.firebaseio.com',
    storageBucket: 'dune-e9f08.appspot.com',
    iosBundleId: 'com.example.dunes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfgan9R6LtVszLeLPQmOfpacXN9bS_WGg',
    appId: '1:925380284779:web:d2e91440b6e6dfd5757c2e',
    messagingSenderId: '925380284779',
    projectId: 'dune-e9f08',
    authDomain: 'dune-e9f08.firebaseapp.com',
    databaseURL: 'https://dune-e9f08-default-rtdb.firebaseio.com',
    storageBucket: 'dune-e9f08.appspot.com',
  );

}